# Generated by Django 5.2.5 on 2025-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='referenceCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Complex', 'Complex'), ('Very Complex', 'Very Complex')], max_length=50)),
                ('per_hour_capacity', models.IntegerField()),
            ],
        ),
    ]
