# Generated by Django 5.2.5 on 2025-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecapacity',
            name='per_hour_capacity',
            field=models.FloatField(),
        ),
    ]
