# Generated by Django 5.2.5 on 2025-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0002_alter_referencecapacity_per_hour_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecapacity',
            name='object_type',
            field=models.CharField(max_length=100),
        ),
    ]
