# Generated by Django 5.2.5 on 2025-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0003_alter_referencecapacity_object_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referencecapacity',
            constraint=models.UniqueConstraint(fields=('object_type', 'level'), name='unique_objectType_level'),
        ),
    ]
