# Generated by Django 5.2.5 on 2025-08-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0004_referencecapacity_unique_objecttype_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencecapacity',
            old_name='per_hour_capacity',
            new_name='capacity_by_one_object',
        ),
    ]
