# Generated by Django 5.2.5 on 2025-08-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0005_rename_per_hour_capacity_referencecapacity_capacity_by_one_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencecapacity',
            old_name='capacity_by_one_object',
            new_name='per_hour_capacity',
        ),
    ]
