# Generated by Django 5.2.5 on 2025-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreSalesCalculator', '0006_rename_capacity_by_one_object_referencecapacity_per_hour_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraSetUpReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Terraform', 'Terraform'), ('Manual', 'Manual'), ('YAML', 'YAML'), ('Other', 'Other')], max_length=50)),
                ('hour_for_one_object', models.IntegerField()),
                ('additional_complexity_hour', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('object_type', 'method'), name='objectType_method')],
            },
        ),
    ]
